# Generated by Django 4.0 on 2022-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
